name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
        postgres:
            # Docker Hub image
            image: postgres:16
            # Provide the password for postgres
            env:
              POSTGRES_USER: root
              POSTGRES_PASSWORD: secret
              POSTGRES_DB: simple_bank
            ports:
              - 5555:5432
            # Set health checks to wait until postgres has started
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.6'
    - name: Set up migration tool
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin
    - name: Migrate db
      run: make migrateup
      
    - name: Test
      run: make test
